version: '3'
services:
    slim-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - /app/vendor
            - .:/app
    composer:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ['composer', 'run', 'test']